### PR TITLE
Add HTCondor

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
To be added after https://github.com/grycap/ansible-role-htcondor/pull/10 is merged

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Question about the following TOSCA code:

```yaml
    artifacts:
      htcondor_role:
        file: grycap.htcondor
        type: tosca.artifacts.AnsibleGalaxy.role
      nfs_role:
        file: grycap.nfs
        type: tosca.artifacts.AnsibleGalaxy.role
```

Does the above lines in `tosca.nodes.indigo.LRMS.FrontEnd.HTCondor` or `tosca.nodes.indigo.LRMS.WorkerNode.HTCondor` trigger Ansible in addition to:

```yaml

    interfaces:
      Standard:
        configure:
          implementation: <playbook>
```

or is it purely a way to express a dependency with no other effect?

**Comment by micafer** [comment]
> Question about the following TOSCA code:
> 
> ```yaml
>     artifacts:
>       htcondor_role:
>         file: grycap.htcondor
>         type: tosca.artifacts.AnsibleGalaxy.role
>       nfs_role:
>         file: grycap.nfs
>         type: tosca.artifacts.AnsibleGalaxy.role
> ```
> 
> Does the above lines in `tosca.nodes.indigo.LRMS.FrontEnd.HTCondor` or `tosca.nodes.indigo.LRMS.WorkerNode.HTCondor` trigger Ansible in addition to:
> 
> ```yaml
>     interfaces:
>       Standard:
>         configure:
>           implementation: <playbook>
> ```
> 
> or is it purely a way to express a dependency with no other effect?

The above lines are used to express a dependency and notify ansible galaxy that these roles must be installed before the execution of the playbooks.

**Comment by sebastian-luna-valero** [comment]
Thanks!

So we need to be careful to avoid duplication (i.e. installing the roles twice)

**Comment by sebastian-luna-valero** [comment]
For example, on this PR I currently have the playbook with:

```yaml

- hosts: localhost
  connection: local
  vars:
     vnode_prefix: vnode-
  roles:
  - role: grycap.nfs
  - role: grycap.htcondor
```

Plus I have added the below to both ` tosca.nodes.indigo.LRMS.FrontEnd.HTCondor` and `tosca.nodes.indigo.LRMS.WorkerNode.HTCondor` in the `custom_types.yam`.

```yaml
    artifacts:
      htcondor_role:
        file: grycap.htcondor
        type: tosca.artifacts.AnsibleGalaxy.role
      nfs_role:
        file: grycap.nfs
        type: tosca.artifacts.AnsibleGalaxy.role
```

That means that the same role will be installed twice, right?

If yes, then I should remove the latter.

**Comment by micafer** [comment]
> For example, on this PR I currently have the playbook with:
> 
> ```yaml
> - hosts: localhost
>   connection: local
>   vars:
>      vnode_prefix: vnode-
>   roles:
>   - role: grycap.nfs
>   - role: grycap.htcondor
> ```
> 

This means that you will call the ansible roles (they must be installed previously from ansible-galaxy).

> Plus I have added the below to both ` tosca.nodes.indigo.LRMS.FrontEnd.HTCondor` and `tosca.nodes.indigo.LRMS.WorkerNode.HTCondor` in the `custom_types.yam`.
> 
> ```yaml
>     artifacts:
>       htcondor_role:
>         file: grycap.htcondor
>         type: tosca.artifacts.AnsibleGalaxy.role
>       nfs_role:
>         file: grycap.nfs
>         type: tosca.artifacts.AnsibleGalaxy.role
> ```
> 
> That means that the same role will be installed twice, right?
No.
> 
> If yes, then I should remove the latter.
No.

You must maintain both, the first one that uses it, and the second one that installs it previously.

You

**Comment by sebastian-luna-valero** [comment]
Right, I see, thanks!

**Pull request merged**
